import './terms.css'
const TermsAndConditions = () => {
  return (
    <div className="terms" style={{ padding: '20px', lineHeight: '1.6', fontFamily: 'Arial, sans-serif' }}>
      <h1>Terms & Conditions</h1>
      
      <p>
        This document is an electronic record in terms of the Information Technology Act, 2000, and the rules thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>
      <p>
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011, which require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name <a href="https://www.pictora.in" target="_blank" rel="noopener noreferrer">pictora.in</a> (Website), including the related mobile site and mobile application (hereinafter referred to as Platform).
      </p>
      <p>
        The Platform is owned by <strong>PICTORA</strong>, a company incorporated under the Companies Act, 1956.
      </p>

      <h2>Introduction</h2>
      <p>
        Your use of the Platform and services and tools is governed by the following terms and conditions (“Terms of Use”) applicable to the Platform, including applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that apply to such transactions. By merely using the Platform, you shall be contracting with the Platform Owner, and these Terms of Use, along with the policies, constitute your binding obligations.
      </p>
      <p>
        These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable) (collectively, `Services`). Any terms and conditions proposed by you that conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
      </p>

      <h2>Services Provided & Pricing</h2>
      <p>
        As a software platform, PICTORA provides the ability for users to create and sell their courses through our platform. For this service, we charge a 13% transaction and platform fee per course transaction. Additionally, we allow users to sell their digital art on our platform, for which we charge up to 11% as a transaction and platform fee. These fees may be subject to change from time to time, so we encourage you to review this section periodically for updates.
      </p>

      <h2>Acceptance</h2>
      <p>
        ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE. PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
      </p>
      
      <h2>Conditions of Use</h2>
      <ul>
        <li>To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration. You shall be responsible for all acts done through the use of your registered account on the Platform.</li>
        <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
        <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</li>
        <li>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. This includes, but is not limited to, the design, layout, look, and graphics.</li>
        <li>Unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
        <li>You agree to pay us the charges associated with availing of the Services.</li>
        <li>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, or Indian or local laws that might apply to you.</li>
        <li>You agree and acknowledge that the website and Services may contain links to other third-party websites. On accessing these links, you will be governed by the terms of use, privacy policy, and such other policies of those third-party websites. These links are provided for your convenience to provide further information.</li>
      </ul>

      <h2>Transactions and Liability</h2>
      <ul>
        <li>By initiating a transaction for availing of the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</li>
        <li>You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable), and their respective officers, directors, agents, and employees from any claim, demand, or actions, including reasonable attorney`s fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, and other Policies, or your violation of any law, rules, or regulations, or the rights (including infringement of intellectual property rights) of a third party.</li>
        <li>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</li>
      </ul>

      <h2>Governing Law</h2>
      <p>
        These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Jangareddygudem, Andhra Pradesh.
      </p>

      <h2>Contact</h2>
      <p>
        All concerns or communications relating to these Terms must be directed to us using the contact information provided on this website.
      </p>
    </div>
  );
};

export default TermsAndConditions;